services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - mysql
      - php
  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel

  mysql:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${MYSQL_PORT}:${DB_PORT}
    volumes:
      - ./src:/var/www/laravel

  composer:
    build:
      context: .docker/composer
      dockerfile: Dockerfile
    working_dir: /var/www/laravel
    volumes:
      - ./src:/var/www/laravel
      - /var/www/laravel/vendor

  artisan:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: [ "php", "/var/www/laravel/artisan" ]

